[project]
name = "module9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.2",
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "swig>=4.4.0",
]
